[package]
name = "miller_rabin"
version = "0.1.0"
authors = ["Xuan <445117445@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.2", features = ["rand"] }
rand = "0.5"

